import { test, expect, type Page } from '@playwright/test'
import { ensureOwnerSession } from '../owner'

async function openContext(page: Page) {
  await page.getByRole('button', { name: '切换详情模块', exact: true }).click()
  await page.getByRole('menuitemradio', { name: '上下文', exact: true }).locator('span').last().click()
  await expect(page.getByRole('region', { name: '会话上下文管理', exact: true })).toBeVisible()
}

async function fixture(page: Page, name: string) {
  return page.evaluate(async name => {
    const headers = { 'Content-Type': 'application/json', Authorization: `Bearer ${localStorage.getItem('roleplex_token')}` }
    async function post(path: string, body: unknown) {
      const response = await fetch(`/api${path}`, { method: 'POST', headers, body: JSON.stringify(body) })
      if (!response.ok) throw new Error(`controlled fixture failed: ${response.status}`)
      return response.json()
    }
    const config = await post('/model-configs', { name, provider_type: 'openai_compatible', api_key: 'fake-context-key' })
    const small = await post('/roles', { name: `${name}短窗口`, model_config_id: config.id, model_name: 'fake-model', system_prompt: '受控角色', context_window_tokens: 4096 })
    const large = await post('/roles', { name: `${name}长窗口`, model_config_id: config.id, model_name: 'fake-model', system_prompt: '受控角色', context_window_tokens: 200000 })
    const group = await post('/conversations', { title: `${name}群聊`, type: 'group', role_ids: [small.id, large.id] })
    const single = await post('/conversations', { title: `${name}单聊`, type: 'single', role_ids: [small.id] })
    await post(`/conversations/${group.id}/messages`, { parts: [{ type: 'text', text: '受控长历史。'.repeat(700) }], mentions: [] })
    await post(`/conversations/${group.id}/messages`, { parts: [{ type: 'text', text: '最近的共同要求' }], mentions: [] })
    return { group: group.id as number, single: single.id as number, small, large }
  }, name)
}

test('群聊共享材料、按角色占用、输入草稿与实际调用可核对，刷新后保留', async ({ page }, info) => {
  page.setDefaultTimeout(12_000); test.setTimeout(90_000)
  await page.setViewportSize({ width: 1680, height: 1050 }); await ensureOwnerSession(page)
  const name = '共享上下文验收', { small, large } = await fixture(page, name)
  await page.reload(); await page.getByRole('button', { name: `打开会话：${name}群聊`, exact: true }).click()
  await openContext(page)
  const usage = page.getByRole('region', { name: '角色上下文占用', exact: true })
  await expect(usage).toContainText('预计有 1 条稳定历史不会发送')
  await expect(usage).toContainText('还没有模型调用记录')
  const ratio = await usage.getByRole('meter').getAttribute('aria-valuetext')
  expect(parseFloat(ratio!)).toBeGreaterThan(100)
  await page.getByLabel('上下文角色', { exact: true }).selectOption(String(large.id))
  await expect(usage).toContainText('采用 2 条历史')
  await expect(usage).not.toContainText('稳定历史不会发送')
  const input = page.getByRole('textbox', { name: '消息输入框', exact: true })
  await input.fill('正在试填的后续要求')
  await expect(usage).toContainText('已计入消息输入框草稿')
  await usage.getByRole('button', { name: '查看输入内容', exact: true }).click()
  const preview = page.getByRole('region', { name: '实际输入预览', exact: true })
  await preview.getByText('4. 本次消息', { exact: true }).click()
  await expect(preview.getByText('正在试填的后续要求', { exact: true })).toBeVisible()
  await usage.getByRole('button', { name: '收起输入内容', exact: true }).click()
  const shot = info.outputPath('conversation-context-usage.png')
  await page.screenshot({ path: shot }); await info.attach('按角色查看共享上下文占用', { path: shot, contentType: 'image/png' })
  await input.fill('@'); await page.getByRole('option', { name: `@${large.name}`, exact: true }).click()
  await input.fill(`@${large.name} 继续执行受控要求`)
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  const call = page.getByRole('region', { name: '最近模型调用上下文', exact: true })
  await expect(call).toContainText('第 1 次调用', { timeout: 20_000 })
  await expect(call).toContainText('已返回')
  await expect(call).toContainText('厂商输入 未知 · 输出 未知')
  await page.getByRole('button', { name: '会话材料', exact: true }).click()
  const materials = page.getByRole('region', { name: '共享会话材料', exact: true })
  await expect(materials).toContainText('稳定 4')
  await page.reload(); await openContext(page)
  await page.getByRole('button', { name: '会话材料', exact: true }).click()
  await expect(materials).toContainText('稳定 4')
  await page.getByRole('button', { name: `打开会话：${name}单聊`, exact: true }).click()
  await openContext(page)
  await expect(usage).toContainText('采用 0 条历史')
  await expect(usage).not.toContainText('稳定历史不会发送')
  await expect(page.getByLabel('上下文角色')).toHaveValue(String(small.id))
})

test('窄屏切换视图保留提示词草稿，读取失败可重试且不展示旧输入', async ({ page }, info) => {
  await page.setViewportSize({ width: 1680, height: 1000 }); await ensureOwnerSession(page)
  const name = '上下文窄屏验收'
  await fixture(page, name)
  await page.reload(); await page.getByRole('button', { name: `打开会话：${name}群聊`, exact: true }).click()
  await openContext(page)
  await page.getByRole('button', { name: '提示词', exact: true }).click()
  await page.getByLabel('会话提示词', { exact: true }).fill('尚未保存的会话约定')
  await page.getByRole('button', { name: '占用与输入', exact: true }).click()
  const usage = page.getByRole('region', { name: '角色上下文占用', exact: true })
  await expect(usage).toContainText('裁剪前预计占用')
  await page.route('**/context/preview', route => route.fulfill({ status: 403, contentType: 'application/json', body: JSON.stringify({ error: { code: 'OWNER_REQUIRED' } }) }))
  await usage.getByRole('button', { name: '刷新上下文', exact: true }).click()
  await expect(usage.getByRole('alert')).toBeVisible()
  await expect(usage.getByRole('meter')).toHaveCount(0)
  await page.unroute('**/context/preview')
  await usage.getByRole('button', { name: '刷新上下文', exact: true }).click()
  await expect(usage.getByRole('meter')).toBeVisible()
  await page.setViewportSize({ width: 390, height: 850 })
  await page.getByRole('button', { name: '收起侧边栏', exact: true }).click()
  await page.getByRole('button', { name: '打开会话详情', exact: true }).click()
  const drawer = page.getByRole('dialog', { name: '会话详情', exact: true })
  await expect(drawer.getByRole('meter')).toBeVisible()
  const shot = info.outputPath('conversation-context-mobile.png')
  await page.screenshot({ path: shot }); await info.attach('窄屏上下文占用', { path: shot, contentType: 'image/png' })
  await drawer.getByRole('button', { name: '提示词', exact: true }).click()
  await expect(drawer.getByLabel('会话提示词', { exact: true })).toHaveValue('尚未保存的会话约定')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: '打开会话详情', exact: true })).toBeFocused()
})
