import { test, expect, type Locator } from '@playwright/test'
import { ensureOwnerSession } from '../owner'

test('React Flow 拖动布局、保存分支环路、恢复及串行启动边界', async ({ page }, testInfo) => {
  page.setDefaultTimeout(10_000)
  await page.setViewportSize({ width: 1440, height: 900 })
  await ensureOwnerSession(page)
  const ids = await page.evaluate(async () => {
    const headers = { 'Content-Type': 'application/json', Authorization: `Bearer ${localStorage.getItem('roleplex_token')}` }
    const post = async (url: string, body: unknown, method = 'POST') => {
      const r = await fetch(url, { method, headers, body: JSON.stringify(body) })
      if (!r.ok) throw new Error(`layout fixture ${r.status}`)
      return r.json()
    }
    const cfg = await post('/api/model-configs', { name: '图编辑配置', provider_type: 'openai_compatible', api_key: 'sk-placeholder' })
    const role = await post('/api/roles', { name: '图编辑角色', model_config_id: cfg.id, model_name: 'fake-model', system_prompt: '受控角色' })
    const conv = await post('/api/conversations', { title: 'React Flow 编辑验收', type: 'single', role_ids: [role.id] })
    const did = crypto.randomUUID()
    await post(`/api/conversations/${conv.id}/workflows/definitions/${did}`, {
      name: '可保存的图', expected_revision: 0, graph: {
        nodes: ['a', 'b', 'c'].map((id, i) => ({ id, title: id.toUpperCase(), kind: 'approval', position: { x: i * 280, y: 80 }, inputs: [] })),
        edges: [['a', 'b'], ['b', 'c']],
      },
    }, 'PUT')
    return { cid: conv.id, did }
  })
  const snapshot = () => page.evaluate(async ({ cid, did }) => {
    const r = await fetch(`/api/conversations/${cid}/workflows`, { headers: { Authorization: `Bearer ${localStorage.getItem('roleplex_token')}` } })
    const data = await r.json()
    return { graph: data.definitions.find((d: { id: string }) => d.id === did).graph, runs: data.runs }
  }, ids)
  async function open() {
    await page.getByRole('button', { name: '切换详情模块', exact: true }).click()
    await page.getByRole('menuitemradio', { name: '工作流', exact: true }).locator('span').last().click()
    await page.getByRole('button', { name: /可保存的图 v/ }).click()
  }
  async function connect(source: Locator, target: Locator) {
    // 等待视口动画结束后按真实鼠标手势连接，避免用动画中的旧坐标。
    await source.dragTo(target)
  }
  await page.reload()
  await page.getByRole('button', { name: '打开会话：React Flow 编辑验收', exact: true }).click()
  await open()
  const canvas = page.getByRole('region', { name: '工作流画布', exact: true })
  const nodeA = canvas.getByRole('button', { name: '节点 1：A', exact: true })
  await nodeA.click()
  const box = await nodeA.boundingBox()
  await page.mouse.move(box!.x + box!.width / 2, box!.y + box!.height / 2)
  await page.mouse.down()
  await page.mouse.move(box!.x + box!.width / 2, box!.y + box!.height / 2 + 110, { steps: 12 })
  await page.mouse.up()
  await nodeA.focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByText(/有未保存编辑/)).toBeVisible()
  await page.getByRole('button', { name: '保存流程', exact: true }).click()
  await expect(page.getByText('已保存版本 2', { exact: true })).toBeVisible()
  const moved = await snapshot()
  expect(moved.graph.nodes[0].position.y).toBeGreaterThan(130)
  expect(moved.graph.nodes[0].position.x).toBeGreaterThan(0)
  expect(moved.graph.nodes.map((n: { id: string }) => n.id)).toEqual(['a', 'b', 'c'])
  expect(moved.graph.edges).toEqual([['a', 'b'], ['b', 'c']])
  await page.reload()
  await open()
  await expect(nodeA).toBeVisible()
  expect(await nodeA.evaluate(el => new DOMMatrixReadOnly((el as HTMLElement).style.transform).m42)).toBeCloseTo(moved.graph.nodes[0].position.y, 2)
  await canvas.getByRole('button', { name: '适配视图', exact: true }).click()
  await connect(canvas.getByLabel('A 输出连接点', { exact: true }), canvas.getByLabel('C 输入连接点', { exact: true }))
  await expect(canvas.locator('.react-flow__edge')).toHaveCount(3)
  await nodeA.click()
  await canvas.getByLabel('节点名称', { exact: true }).fill('A 修改')
  await page.getByRole('button', { name: '保存流程', exact: true }).click()
  await expect(page.getByText('已保存版本 3', { exact: true })).toBeVisible()
  expect((await snapshot()).graph.edges).toHaveLength(3)
  await page.getByRole('button', { name: '启动流程', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('当前仅支持完整串行路径运行')
  expect((await snapshot()).runs).toHaveLength(0)
  await page.getByText('连线工具', { exact: true }).click()
  await page.getByLabel('连线起点', { exact: true }).selectOption('c')
  await page.getByLabel('连线终点', { exact: true }).selectOption('a')
  await page.getByRole('button', { name: '连接节点', exact: true }).click()
  await expect(canvas.locator('.react-flow__edge')).toHaveCount(4)
  await page.getByRole('button', { name: '保存流程', exact: true }).click()
  await expect(page.getByText('已保存版本 4', { exact: true })).toBeVisible()
  await page.reload()
  await open()
  await expect(canvas.locator('.react-flow__edge')).toHaveCount(4)
  await page.getByRole('button', { name: '启动流程', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('当前仅支持完整串行路径运行')
  expect((await snapshot()).runs).toHaveLength(0)
  const shot = testInfo.outputPath('react-flow-branches-cycle.png')
  await canvas.screenshot({ path: shot })
  await testInfo.attach('保存并恢复分支环路', { path: shot, contentType: 'image/png' })
  await page.getByText('连线工具', { exact: true }).click()
  for (const edge of [['a', 'c'], ['c', 'a']]) {
    await page.getByLabel('选择连线', { exact: true }).selectOption(JSON.stringify(edge))
    await page.getByRole('button', { name: '删除连线', exact: true }).click()
  }
  await page.getByRole('button', { name: '保存流程', exact: true }).click()
  await expect(page.getByText('已保存版本 5', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '启动流程', exact: true }).click()
  await expect(page.getByText(/等待人工确认 · 定义快照/)).toBeVisible()
  await expect(canvas.locator('.react-flow__node.draggable')).toHaveCount(0)
  await expect(page.getByText('连线工具', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '停止此运行', exact: true }).click()
  await expect(page.getByText(/已停止 · 定义快照/)).toBeVisible()
})

test('Delete 删除选中连线和孤立节点，保护连接节点、文本输入和运行视图', async ({ page }) => {
  page.setDefaultTimeout(10_000)
  await page.setViewportSize({ width: 1440, height: 900 })
  await ensureOwnerSession(page)
  const cid = await page.evaluate(async () => {
    const headers = { 'Content-Type': 'application/json', Authorization: `Bearer ${localStorage.getItem('roleplex_token')}` }
    const post = async (url: string, body: unknown, method = 'POST') => {
      const r = await fetch(url, { method, headers, body: JSON.stringify(body) })
      if (!r.ok) throw new Error(`delete fixture ${r.status}`)
      return r.json()
    }
    const cfg = await post('/api/model-configs', { name: '快捷键配置', provider_type: 'openai_compatible', api_key: 'sk-placeholder' })
    const role = await post('/api/roles', { name: '快捷键角色', model_config_id: cfg.id, model_name: 'fake-model', system_prompt: '受控角色' })
    const conv = await post('/api/conversations', { title: 'Delete 快捷键验收', type: 'single', role_ids: [role.id] })
    await post(`/api/conversations/${conv.id}/workflows/definitions/${crypto.randomUUID()}`, {
      name: '删除测试', expected_revision: 0, graph: {
        nodes: ['a', 'b', 'c', 'd'].map((id, i) => ({ id, title: id.toUpperCase(), kind: 'approval', inputs: id === 'a' ? ['d'] : [], position: { x: (i % 2) * 300, y: Math.floor(i / 2) * 240 } })),
        edges: [['a', 'b'], ['c', 'c']],
      },
    }, 'PUT')
    return conv.id as number
  })
  await page.reload()
  await page.getByRole('button', { name: '打开会话：Delete 快捷键验收', exact: true }).click()
  await page.getByRole('button', { name: '切换详情模块', exact: true }).click()
  await page.getByRole('menuitemradio', { name: '工作流', exact: true }).locator('span').last().click()
  await page.getByRole('button', { name: /删除测试 v1/ }).click()
  const canvas = page.getByRole('region', { name: '工作流画布', exact: true })
  const node = (name: string) => canvas.getByRole('button', { name: new RegExp(`节点 \\d+：${name}$`) })
  await node('B').click()
  await expect(canvas.getByRole('button', { name: '删除', exact: true })).toBeDisabled()
  await node('B').focus()
  await page.keyboard.press('Delete')
  await expect(canvas.getByRole('status')).toContainText('节点仍有连线')
  await expect(canvas.locator('.react-flow__node')).toHaveCount(4)
  await expect(canvas.locator('.react-flow__edge')).toHaveCount(2)
  // 自环也是连接，不可隐式连带删除。
  await node('C').click()
  await node('C').focus()
  await page.keyboard.press('Delete')
  await expect(node('C')).toBeVisible()
  await expect(canvas.locator('.react-flow__edge')).toHaveCount(2)
  await node('D').click()
  await page.getByLabel('流程名称', { exact: true }).fill('文字测试')
  await page.keyboard.press('Home')
  await page.keyboard.press('Delete')
  await expect(page.getByLabel('流程名称', { exact: true })).toHaveValue('字测试')
  await expect(node('D')).toBeVisible()
  await canvas.getByRole('button', { name: '返回对话', exact: true }).focus()
  await page.keyboard.press('Delete')
  await expect(node('D')).toBeVisible()
  await node('D').focus()
  await page.keyboard.press('Delete')
  await expect(node('D')).toHaveCount(0)
  await expect(canvas.locator('.react-flow__edge')).toHaveCount(2)
  const ab = canvas.getByRole('group', { name: '连线：A → B', exact: true })
  await ab.focus()
  await page.keyboard.press('Enter')
  await page.keyboard.press('Delete')
  await expect(canvas.locator('.react-flow__edge')).toHaveCount(1)
  await expect(node('A')).toBeVisible()
  await expect(node('B')).toBeVisible()
  await node('B').click()
  await node('B').focus()
  await page.keyboard.press('Delete')
  await expect(node('B')).toHaveCount(0)
  const loop = canvas.getByRole('group', { name: '连线：C → C', exact: true })
  await loop.focus()
  await page.keyboard.press('Enter')
  await page.keyboard.press('Delete')
  await expect(canvas.locator('.react-flow__edge')).toHaveCount(0)
  await node('C').click()
  await canvas.getByRole('button', { name: '删除', exact: true }).click()
  await expect(node('C')).toHaveCount(0)
  await page.getByRole('button', { name: '保存流程', exact: true }).click()
  await expect(page.getByText('已保存版本 2', { exact: true })).toBeVisible()
  const saved = await page.evaluate(async cid => {
    const response = await fetch(`/api/conversations/${cid}/workflows`, { headers: { Authorization: `Bearer ${localStorage.getItem('roleplex_token')}` } })
    return (await response.json()).definitions[0].graph
  }, cid)
  expect(saved.nodes).toHaveLength(1)
  expect(saved.nodes[0].inputs).toEqual([])
  await page.getByRole('button', { name: '启动流程', exact: true }).click()
  await expect(page.getByText(/等待人工确认 · 定义快照/)).toBeVisible()
  await node('A').click()
  await node('A').focus()
  await page.keyboard.press('Delete')
  await expect(node('A')).toBeVisible()
  await expect(canvas.getByRole('button', { name: '删除', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '停止此运行', exact: true }).click()
  await expect(page.getByText(/已停止 · 定义快照/)).toBeVisible()
})
