import { test, expect } from '@playwright/test'
import { ensureOwnerSession } from '../owner'
import { closeWorkflowDrawer, openWorkflowTemplate, saveWorkflow, startWorkflow, workflowInspector, workflowMore, workflowOverview, workflowToolbar } from '../workflow-ui'

test('侧栏操作、Tab 插入、类型颜色保存与窄屏抽屉', async ({ page }, testInfo) => {
  page.setDefaultTimeout(10_000)
  await page.setViewportSize({ width: 1440, height: 900 })
  await ensureOwnerSession(page)
  const cid = await page.evaluate(async () => {
    const headers = { 'Content-Type': 'application/json', Authorization: `Bearer ${localStorage.getItem('roleplex_token')}` }
    const post = async (url: string, body: unknown, method = 'POST') => {
      const response = await fetch(url, { method, headers, body: JSON.stringify(body) })
      if (!response.ok) throw new Error(`node fixture ${response.status}`)
      return response.json()
    }
    const cfg = await post('/api/model-configs', { name: '节点编辑配置', provider_type: 'openai_compatible', api_key: 'sk-placeholder' })
    const role = await post('/api/roles', { name: '节点编辑角色', model_config_id: cfg.id, model_name: 'fake-model', system_prompt: '受控角色' })
    const conv = await post('/api/conversations', { type: 'single', title: '侧栏与节点验收', role_ids: [role.id] })
    await post(`/api/conversations/${conv.id}/workflows/definitions/${crypto.randomUUID()}`, {
      name: '节点外观与编辑', expected_revision: 0, graph: { nodes: [
        { id: 'a', kind: 'approval', title: '开始确认', inputs: [], position: { x: 0, y: 80 } },
        { id: 'b', kind: 'approval', title: '结束确认', inputs: ['a'], position: { x: 280, y: 80 } },
      ], edges: [['a', 'b']] },
    }, 'PUT')
    return conv.id as number
  })
  await page.reload()
  await page.getByRole('button', { name: '打开会话：侧栏与节点验收', exact: true }).click()
  await openWorkflowTemplate(page, '节点外观与编辑')
  const canvas = page.getByRole('region', { name: '工作流画布', exact: true })
  const sidebar = page.getByRole('complementary', { name: '会话详情', exact: true })
  for (const name of ['保存模板', '启动流程']) {
    await expect(workflowToolbar(page).getByRole('button', { name, exact: true })).toBeVisible()
    await expect(sidebar.getByRole('button', { name, exact: true })).toHaveCount(0)
  }
  await expect(page.getByRole('button', { name: '编辑流程', exact: true })).toHaveCount(0)
  await expect(canvas.getByLabel('流程名称', { exact: true })).toHaveCount(0)
  await expect(canvas.getByText('连线工具', { exact: true })).toHaveCount(0)
  await canvas.getByRole('button', { name: '节点 1：开始确认', exact: true }).click()
  await canvas.getByRole('button', { name: '节点 1：开始确认', exact: true }).focus()
  await page.keyboard.press('Tab')
  await expect(canvas.locator('.react-flow__node')).toHaveCount(3)
  let inserted = canvas.getByRole('button', { name: '节点 2：角色任务', exact: true })
  await expect(inserted).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(canvas.locator('.react-flow__node')).toHaveCount(3)
  await inserted.click()
  await workflowInspector(page).getByLabel('本步任务', { exact: true }).fill('保留这段任务文字')
  await page.keyboard.press('Tab')
  await expect(canvas.locator('.react-flow__node')).toHaveCount(3)
  await expect(workflowInspector(page).getByLabel('节点颜色', { exact: true })).toHaveValue('#4385a0')
  await workflowInspector(page).getByLabel('节点类型', { exact: true }).selectOption('approval')
  await expect(workflowInspector(page).getByLabel('本步任务', { exact: true })).toHaveCount(0)
  await expect(workflowInspector(page).getByLabel('节点颜色', { exact: true })).toHaveValue('#b58b45')
  await workflowInspector(page).getByLabel('节点颜色', { exact: true }).fill('#8040c0')
  await workflowInspector(page).getByLabel('节点类型', { exact: true }).selectOption('role')
  await expect(workflowInspector(page).getByLabel('本步任务', { exact: true })).toHaveValue('保留这段任务文字')
  await expect(workflowInspector(page).getByLabel('节点颜色', { exact: true })).toHaveValue('#8040c0')
  await workflowInspector(page).getByRole('button', { name: '恢复默认颜色', exact: true }).click()
  await expect(workflowInspector(page).getByLabel('节点颜色', { exact: true })).toHaveValue('#4385a0')
  await workflowInspector(page).getByLabel('节点类型', { exact: true }).selectOption('approval')
  await workflowInspector(page).getByLabel('节点颜色', { exact: true }).fill('#537f4f')
  await saveWorkflow(page)
  await expect(workflowToolbar(page).getByText('版本 2', { exact: true })).toBeVisible()
  const graph = await page.evaluate(async cid => {
    const r = await fetch(`/api/conversations/${cid}/workflows`, { headers: { Authorization: `Bearer ${localStorage.getItem('roleplex_token')}` } })
    return (await r.json()).definitions[0].graph
  }, cid)
  expect(graph.nodes).toHaveLength(3)
  expect(graph.edges).toEqual([['a', graph.nodes[1].id], [graph.nodes[1].id, 'b']])
  expect(graph.nodes[1]).toMatchObject({ kind: 'approval', role_id: null, color: '#537f4f', task: '保留这段任务文字' })
  await page.reload()
  await workflowOverview(page)
  await expect(page.getByLabel('流程名称', { exact: true })).toHaveValue('节点外观与编辑')
  inserted = canvas.getByRole('button', { name: '节点 2：人工确认', exact: true })
  await inserted.click()
  await expect(workflowInspector(page).getByLabel('节点颜色', { exact: true })).toHaveValue('#537f4f')
  await expect(inserted.locator('.workflow-task')).toHaveCSS('border-top-color', 'rgb(83, 127, 79)')
  const shot = testInfo.outputPath('sidebar-and-node-colors.png')
  await page.screenshot({ path: shot })
  await testInfo.attach('侧栏操作与节点颜色', { path: shot, contentType: 'image/png' })

  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: '收起侧边栏', exact: true }).click()
  await workflowToolbar(page).getByRole('button', { name: '详情', exact: true }).click()
  const drawer = page.getByRole('dialog', { name: '会话详情', exact: true })
  await drawer.getByRole('button', { name: '流程概况', exact: true }).click()
  await drawer.getByLabel('流程名称', { exact: true }).fill('窄屏流程修改')
  await saveWorkflow(page)
  await expect(workflowToolbar(page).getByText('版本 3', { exact: true })).toBeVisible()
  await workflowMore(page, '添加角色任务')
  await expect(drawer).toBeVisible()
  await expect(workflowInspector(page).getByLabel('本步任务', { exact: true })).toBeVisible()
  await workflowInspector(page).getByLabel('本步任务', { exact: true }).fill('窄屏新增任务')
  await saveWorkflow(page)
  await expect(workflowToolbar(page).getByText('版本 4', { exact: true })).toBeVisible()
  await startWorkflow(page)
  await expect(drawer).toHaveCount(0)
  await expect(canvas.locator('.react-flow__node')).toHaveCount(4)
  await expect(workflowToolbar(page).getByRole('status')).toContainText('等待人工确认')
  await canvas.getByLabel('定位节点', { exact: true }).selectOption('a')
  await canvas.getByRole('button', { name: '节点 1：开始确认', exact: true }).click()
  await canvas.getByRole('button', { name: '节点 1：开始确认', exact: true }).focus()
  await page.keyboard.press('Tab')
  await expect(canvas.locator('.react-flow__node')).toHaveCount(4)
  await expect(workflowInspector(page).getByLabel('节点类型', { exact: true })).toHaveCount(0)
  await expect(workflowToolbar(page).getByRole('status')).toContainText('等待人工确认')
  const runTarget = await workflowToolbar(page).getByLabel('工作流对象').inputValue()
  await workflowMore(page, '编辑原模板')
  await workflowOverview(page)
  await expect(drawer.getByLabel('流程名称', { exact: true })).toHaveValue('窄屏流程修改')
  await expect(drawer.getByRole('button', { name: '编辑流程', exact: true })).toHaveCount(0)
  await closeWorkflowDrawer(page)
  await workflowToolbar(page).getByLabel('工作流对象').selectOption(runTarget)
  await workflowToolbar(page).getByRole('button', { name: '停止运行', exact: true }).click()
  await expect(workflowToolbar(page).getByRole('status')).toContainText('已停止')
})
