import { expect, test } from '@playwright/test'
import { mkdir, readFile } from 'node:fs/promises'
import path from 'node:path'
import { ensureOwnerSession } from '../owner'
import { openWorkflowTemplate, saveWorkflow, startWorkflow, workflowInspector, workflowMore, workflowToolbar } from '../workflow-ui'

test('画布编排、人工确认、文件交接与返回聊天保留草稿', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  const root = path.join(process.env.ROLEPLEX_COMMAND_E2E_WORKSPACE!, 'workflow-canvas')
  await mkdir(root, { recursive: true })
  await ensureOwnerSession(page)
  const ids = await page.evaluate(async root => {
    const headers = { 'Content-Type': 'application/json', Authorization: `Bearer ${localStorage.getItem('roleplex_token')}` }
    const post = async (url: string, data: unknown, method = 'POST') => {
      const r = await fetch(url, { method, headers, body: JSON.stringify(data) })
      if (!r.ok) throw new Error(`workflow fixture ${r.status}`)
      return r.json()
    }
    const config = await post('/api/model-configs', { name: '工作流模型', provider_type: 'openai_compatible', api_key: 'sk-placeholder' })
    const writer = await post('/api/roles', { name: '流程开发者', model_config_id: config.id, model_name: 'fake-model', system_prompt: '写入', builtin_tools: ['workspace_write'] })
    const editor = await post('/api/roles', { name: '流程审查者', model_config_id: config.id, model_name: 'fake-model', system_prompt: '审查', builtin_tools: ['workspace_read', 'workspace_edit'] })
    const binding = await post('/api/workspaces', { display_name: '流程目录', root_path: root, acknowledge_existing_content: true })
    await post(`/api/workspaces/${binding.id}`, { file_tools_enabled: true }, 'PATCH')
    const conv = await post('/api/conversations', { title: '可操作工作流验收', type: 'group', role_ids: [writer.id, editor.id], workspace_binding_id: binding.id })
    return { cid: conv.id, writer: writer.id, editor: editor.id }
  }, root)
  await page.reload()
  await page.getByRole('button', { name: '打开会话：可操作工作流验收', exact: true }).click()
  await page.getByLabel('消息输入框').fill('未发送的聊天草稿')
  await page.getByRole('button', { name: '切换详情模块', exact: true }).click()
  await page.getByRole('menuitemradio', { name: '工作流', exact: true }).locator('span').last().click()
  await page.getByRole('button', { name: '新建工作流', exact: true }).click()
  const canvas = page.getByRole('region', { name: '工作流画布', exact: true })
  await expect(canvas).toBeVisible()
  await expect(page.getByRole('textbox', { name: '消息输入框' })).toHaveCount(0)
  await page.getByLabel('流程名称', { exact: true }).fill('开发与审查')
  await workflowMore(page, '添加角色任务')
  await workflowInspector(page).getByLabel('节点名称', { exact: true }).fill('开发')
  await workflowInspector(page).getByLabel('执行角色', { exact: true }).selectOption(String(ids.writer))
  await workflowInspector(page).getByLabel('本步任务', { exact: true }).fill('[GROUP_FILES_FAKE]')
  await workflowMore(page, '添加人工确认')
  await workflowInspector(page).getByLabel('节点名称', { exact: true }).fill('人工核对')
  await workflowMore(page, '添加角色任务')
  await workflowInspector(page).getByLabel('节点名称', { exact: true }).fill('审查')
  await workflowInspector(page).getByLabel('执行角色', { exact: true }).selectOption(String(ids.editor))
  await workflowInspector(page).getByLabel('本步任务', { exact: true }).fill('[GROUP_FILES_FAKE]')
  await workflowInspector(page).getByRole('checkbox', { name: '开发', exact: true }).check()
  await saveWorkflow(page)
  await expect(workflowToolbar(page).getByText('版本 1', { exact: true })).toBeVisible()
  await startWorkflow(page)
  await expect(workflowToolbar(page).getByRole('status')).toContainText('等待人工确认', { timeout: 20_000 })
  expect(await readFile(path.join(root, 'group.txt'), 'utf8')).toBe('first')
  await canvas.getByRole('button', { name: '返回对话', exact: true }).click()
  await expect(page.getByLabel('消息输入框')).toHaveValue('未发送的聊天草稿')
  await expect(page.getByText('群聊写入角色完成。', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '打开工作流', exact: true }).click()
  await canvas.getByRole('button', { name: '节点 2：人工核对', exact: true }).click()
  await workflowInspector(page).getByRole('button', { name: '确认继续', exact: true }).click()
  await expect(workflowToolbar(page).getByRole('status')).toContainText('本次执行结束', { timeout: 20_000 })
  expect(await readFile(path.join(root, 'group.txt'), 'utf8')).toBe('second')
  await canvas.getByRole('button', { name: '节点 3：审查', exact: true }).click()
  await workflowInspector(page).getByRole('button', { name: '查看结果与执行事实', exact: true }).click()
  const detail = page.getByRole('dialog', { name: '节点尝试详情' })
  await expect(detail.getByText('服务器核对事实', { exact: true })).toBeVisible()
  await expect(detail.getByRole('region', { name: '文件差异：group.txt' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(detail).toHaveCount(0)
  const shot = testInfo.outputPath('workflow-canvas.png')
  await canvas.screenshot({ path: shot })
  await testInfo.attach('实际运行画布', { path: shot, contentType: 'image/png' })
  await page.reload()
  await expect(workflowToolbar(page)).toBeVisible()
  await expect(workflowToolbar(page).getByRole('status')).toContainText('本次执行结束')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: '收起侧边栏', exact: true }).click()
  await expect(page.getByRole('complementary', { name: '工作区侧栏' })).toBeHidden()
  await expect(canvas.getByRole('button', { name: '返回对话', exact: true })).toBeVisible()
  await canvas.getByRole('button', { name: '适配视图', exact: true }).click()
  // 第一次 Esc 清除恢复后的节点选择，第二次才返回对话。
  await page.keyboard.press('Escape')
  await page.keyboard.press('Escape')
  await expect(canvas).toHaveCount(0)
})

test('已提交后停止、刷新恢复并重试人工节点，不重放开发节点', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  const root = path.join(process.env.ROLEPLEX_COMMAND_E2E_WORKSPACE!, 'workflow-retry')
  await mkdir(root, { recursive: true })
  await ensureOwnerSession(page)
  const cid = await page.evaluate(async root => {
    const headers = { 'Content-Type': 'application/json', Authorization: `Bearer ${localStorage.getItem('roleplex_token')}` }
    const post = async (url: string, data: unknown, method = 'POST') => {
      const response = await fetch(url, { method, headers, body: JSON.stringify(data) })
      if (!response.ok) throw new Error(`retry fixture ${response.status}`)
      return response.json()
    }
    const cfg = await post('/api/model-configs', { name: '重试模型', provider_type: 'openai_compatible', api_key: 'sk-placeholder' })
    const writer = await post('/api/roles', { name: '重试开发者', model_config_id: cfg.id, model_name: 'fake-model', system_prompt: '开发', builtin_tools: ['workspace_write'] })
    const editor = await post('/api/roles', { name: '重试审查者', model_config_id: cfg.id, model_name: 'fake-model', system_prompt: '审查', builtin_tools: ['workspace_read', 'workspace_edit'] })
    const ws = await post('/api/workspaces', { display_name: '重试目录', root_path: root, acknowledge_existing_content: true })
    await post(`/api/workspaces/${ws.id}`, { file_tools_enabled: true }, 'PATCH')
    const conv = await post('/api/conversations', { title: '工作流停止重试', type: 'group', role_ids: [writer.id, editor.id], workspace_binding_id: ws.id })
    await post(`/api/conversations/${conv.id}/workflows/definitions/${crypto.randomUUID()}`, {
      name: '停止后恢复审查', expected_revision: 0, graph: { nodes: [
        { id: 'a', kind: 'role', title: '开发', role_id: writer.id, task: '[GROUP_FILES_FAKE]', inputs: [] },
        { id: 'b', kind: 'approval', title: '人工核对', inputs: ['a'] },
        { id: 'c', kind: 'role', title: '审查', role_id: editor.id, task: '[GROUP_FILES_FAKE]', inputs: ['a'] },
      ], edges: [['a', 'b'], ['b', 'c']] },
    }, 'PUT')
    return conv.id as number
  }, root)
  await page.reload()
  await page.getByRole('button', { name: '打开会话：工作流停止重试', exact: true }).click()
  await openWorkflowTemplate(page, '停止后恢复审查')
  const canvas = page.getByRole('region', { name: '工作流画布', exact: true })
  await startWorkflow(page)
  await expect(workflowToolbar(page).getByRole('status')).toContainText('等待人工确认', { timeout: 20_000 })
  expect(await readFile(path.join(root, 'group.txt'), 'utf8')).toBe('first')
  await page.getByRole('button', { name: '停止运行', exact: true }).click()
  await expect(workflowToolbar(page).getByRole('status')).toContainText('已停止')
  const rid = (await workflowToolbar(page).getByLabel('工作流对象').inputValue()).replace('run:', '')
  await page.reload()
  await expect(workflowToolbar(page).getByLabel('工作流对象')).toHaveValue(`run:${rid}`)
  await canvas.getByRole('button', { name: '节点 2：人工核对', exact: true }).click()
  await workflowInspector(page).getByRole('button', { name: '查看结果与执行事实', exact: true }).click()
  const detail = page.getByRole('dialog', { name: '节点尝试详情' })
  await expect(detail.getByText('服务器核对事实', { exact: true })).toBeVisible()
  await detail.getByRole('checkbox', { name: /我已核对本次结果/ }).check()
  await detail.getByRole('checkbox', { name: /本节点结束后重新执行后续步骤/ }).check()
  await detail.getByRole('button', { name: '创建新尝试', exact: true }).click()
  await detail.getByRole('button', { name: '关闭尝试详情', exact: true }).click()
  await expect(workflowInspector(page).getByRole('button', { name: '确认继续', exact: true })).toBeVisible()
  await workflowInspector(page).getByRole('button', { name: '确认继续', exact: true }).click()
  await expect(workflowToolbar(page).getByRole('status')).toContainText('本次执行结束', { timeout: 20_000 })
  expect(await readFile(path.join(root, 'group.txt'), 'utf8')).toBe('second')
  const counts = await page.evaluate(async ({ cid, rid }) => {
    const response = await fetch(`/api/conversations/${cid}/workflows`, { headers: { Authorization: `Bearer ${localStorage.getItem('roleplex_token')}` } })
    const run = (await response.json()).runs.find((r: { id: string }) => r.id === rid)
    return run.attempts.map((a: { node_id: string }) => a.node_id)
  }, { cid, rid })
  expect(counts.filter((id: string) => id === 'a')).toHaveLength(1)
  expect(counts.filter((id: string) => id === 'b')).toHaveLength(2)
})
