import { test, expect } from '@playwright/test'
import { ensureOwnerSession } from '../owner'

test('创建专用类型并配置初始化，重启后资源与真实模型材料保持一致', async ({ page }, info) => {
  test.setTimeout(100000); page.setDefaultTimeout(15000)
  await page.setViewportSize({ width: 1440, height: 1000 }); await ensureOwnerSession(page)
  const source = await page.evaluate(async () => (await (await fetch('/api/health')).json()).world_name as string)
  const target = `类型验收-${process.env.ROLEPLEX_E2E_STAMP}`
  await page.getByRole('button', { name: /管理运行世界与存储/ }).click()
  await page.getByLabel('世界类型', { exact: true }).selectOption('fixture')
  await page.getByLabel('世界名称', { exact: true }).fill(target)
  await page.getByRole('button', { name: '创建世界', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: `世界“${target}”已创建` })).toBeVisible()
  page.once('dialog', dialog => dialog.accept())
  await page.getByLabel('切换世界', { exact: true }).selectOption(target)
  await expect(page.getByRole('button', { name: '登录', exact: true })).toBeVisible({ timeout: 30000 })
  await ensureOwnerSession(page)
  const identity = await page.evaluate(async () => (await fetch('/api/health')).json())
  expect(identity.world_type).toBe('fixture'); expect(identity.type_version).toBe(1)
  await page.evaluate(async () => {
    const response = await fetch('/api/model-configs', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${localStorage.getItem('roleplex_token')}` },
      body: JSON.stringify({ name: '类型验收模型', provider_type: 'openai_compatible', api_key: 'sk-placeholder' }) })
    if (!response.ok) throw new Error('controlled type model setup failed')
  })
  await page.reload(); await page.getByRole('button', { name: /管理运行世界与存储/ }).click()
  const panel = page.getByRole('region', { name: '当前世界类型', exact: true })
  await expect(panel).toContainText('需要补充配置')
  await expect(panel.getByRole('region', { name: '受控类型专页' })).toBeVisible()
  await panel.getByLabel('样例名称', { exact: true }).fill('TYPE_FIXTURE_ALPHA')
  await panel.getByLabel('类型使用的模型', { exact: true }).selectOption({ label: '类型验收模型' })
  await panel.getByRole('button', { name: '保存类型配置', exact: true }).click()
  await expect(panel).toContainText('初始化完成')
  const shot = info.outputPath('world-type-initialized.png')
  await page.screenshot({ path: shot }); await info.attach('专属类型初始化与扩展页面', { path: shot, contentType: 'image/png' })
  await panel.getByRole('button', { name: '打开类型会话', exact: true }).click()
  await page.getByRole('textbox', { name: '消息输入框', exact: true }).fill('[WORLD_TYPE_PROBE] 查看本类型提供的资料')
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  await expect(page.getByText(/^世界类型资料核对：/)).toContainText('TYPE_FIXTURE_CONTEXT TYPE_FIXTURE_ALPHA')
  const read = async () => page.evaluate(async () => {
    const headers = { Authorization: `Bearer ${localStorage.getItem('roleplex_token')}` }
    return { state: await (await fetch('/api/world-type', { headers })).json(), roles: await (await fetch('/api/roles', { headers })).json() }
  })
  const before = await read()
  await page.getByRole('button', { name: '打开世界协调面板', exact: true }).click()
  const coordinator = page.getByRole('dialog', { name: '世界协调面板', exact: true })
  await coordinator.getByLabel('导入世界管理者配置', { exact: true }).selectOption(String(before.state.initialization.resources.coordinator_role_id))
  await coordinator.getByLabel('世界协调输入', { exact: true }).fill('TYPE_WORLD_COORDINATION_PERSISTED')
  await coordinator.getByRole('button', { name: '发送世界协调消息', exact: true }).click()
  await expect(coordinator.getByRole('region', { name: '世界协调对话' })).toContainText('收到你的消息：TYPE_WORLD_COORDINATION_PERSISTED')
  await coordinator.getByRole('button', { name: '收起世界协调面板', exact: true }).click()
  await page.getByRole('button', { name: /管理运行世界与存储/ }).click()
  page.once('dialog', dialog => dialog.accept()); await page.getByLabel('切换世界', { exact: true }).selectOption(source)
  await expect(page.getByRole('button', { name: '登录', exact: true })).toBeVisible({ timeout: 30000 }); await ensureOwnerSession(page)
  await page.getByRole('button', { name: '打开世界协调面板', exact: true }).click()
  await expect(coordinator).not.toContainText('TYPE_WORLD_COORDINATION_PERSISTED')
  await coordinator.getByRole('button', { name: '收起世界协调面板', exact: true }).click()
  await page.getByRole('button', { name: /管理运行世界与存储/ }).click()
  page.once('dialog', dialog => dialog.accept()); await page.getByLabel('切换世界', { exact: true }).selectOption(target)
  await expect(page.getByRole('button', { name: '登录', exact: true })).toBeVisible({ timeout: 30000 }); await ensureOwnerSession(page)
  const after = await read()
  expect(after.state.initialization.resources).toEqual(before.state.initialization.resources)
  expect(after.state.revision).toBe(before.state.revision)
  expect(after.roles.map((role: { id: number }) => role.id)).toEqual(before.roles.map((role: { id: number }) => role.id))
  await page.getByRole('button', { name: '打开世界协调面板', exact: true }).click()
  await expect(coordinator).toContainText('TYPE_WORLD_COORDINATION_PERSISTED')
  await expect(coordinator).toContainText('世界管理者')
  await coordinator.getByRole('button', { name: '收起世界协调面板', exact: true }).click()
  await page.getByRole('button', { name: /管理运行世界与存储/ }).click()
  page.once('dialog', dialog => dialog.accept()); await page.getByLabel('切换世界', { exact: true }).selectOption(source)
  await expect(page.getByRole('button', { name: '登录', exact: true })).toBeVisible({ timeout: 30000 })
})
