import { test, expect } from '@playwright/test'
import { ensureOwnerSession } from './owner'
import { execFileSync } from 'node:child_process'
import path from 'node:path'

const base = process.env.ROLEPLEX_E2E_API_ORIGIN!

test('右侧模块扇形切换、键盘关闭和窄屏抽屉保留会话草稿', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await ensureOwnerSession(page)
  const cid = await page.evaluate(async (base) => {
    const headers = { 'Content-Type': 'application/json', Authorization: `Bearer ${localStorage.getItem('roleplex_token')}` }
    const post = async (route: string, body: unknown) => {
      const response = await fetch(base + route, { method: 'POST', headers, body: JSON.stringify(body) })
      if (!response.ok) throw new Error('详情测试准备失败')
      return response.json()
    }
    const model = await post('/api/model-configs', { name: '详情模型', provider_type: 'openai_compatible', api_key: 'sk-placeholder' })
    const role = await post('/api/roles', { name: '详情助手', model_config_id: model.id, model_name: 'fake-model', system_prompt: '受控助手。', description: '协助整理灵感。\n'.repeat(80) })
    return (await post('/api/conversations', { title: '扇形详情验收', type: 'single', role_ids: [role.id] })).id as number
  }, base)
  await page.reload()
  await page.getByRole('button', { name: '打开会话：扇形详情验收', exact: true }).click()
  const panel = page.getByRole('complementary', { name: '会话详情', exact: true })
  await expect(panel.getByRole('heading', { name: '会话概览' })).toBeVisible()
  await expect(panel).toContainText('未绑定工作区')
  await page.getByLabel('消息输入框').fill('保留当前草稿')
  const trigger = page.getByRole('button', { name: '切换详情模块', exact: true })
  const triggerBox = await trigger.boundingBox()
  await trigger.click()
  await expect(trigger).toHaveCount(0)
  const menu = page.getByRole('menu', { name: '详情模块' })
  await expect(menu.getByRole('menuitemradio')).toHaveCount(5)
  await expect(menu.getByRole('menuitemradio', { name: '未开放' })).toHaveCount(3)
  for (const item of await menu.getByRole('menuitemradio', { name: '未开放' }).all()) await expect(item).toBeDisabled()
  await expect(panel.getByRole('button', { name: '收起会话详情' })).toHaveCount(0)
  await expect(menu).toHaveCSS('opacity', '1')
  await page.mouse.click(triggerBox!.x + triggerBox!.width / 2, triggerBox!.y + triggerBox!.height / 2)
  await expect(menu).toBeVisible()
  await menu.getByRole('menuitemradio', { name: '会话概览' }).locator('span').last().click()
  await expect(menu).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await trigger.click()

  const origin = await panel.boundingBox()
  const fan = await menu.boundingBox()
  expect(Math.abs(fan!.x + fan!.width - (origin!.x + origin!.width))).toBeLessThan(1)
  expect(Math.abs(fan!.y - origin!.y)).toBeLessThan(1)
  expect(Math.abs(fan!.width - origin!.width)).toBeLessThanOrEqual(1)
  const background = await panel.evaluate(element => getComputedStyle(element).backgroundColor)
  for (const item of await menu.getByRole('menuitemradio').all()) await expect(item).toHaveCSS('background-color', background)
  const shot = testInfo.outputPath('details-fan.png')
  await page.screenshot({ path: shot })
  await testInfo.attach('右上扇形模块选择', { path: shot, contentType: 'image/png' })
  // 透明外角不拦截点击，选择模块后以顺时针循环进入标题位置。
  await page.mouse.click(fan!.x + 4, fan!.y + fan!.height - 4)
  await expect(menu).toHaveCount(0)
  await trigger.click()
  await page.keyboard.press('ArrowDown')
  await expect(menu.getByRole('menuitemradio', { name: '会话成员' })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(menu).toHaveCount(0)
  await expect(panel.getByRole('heading', { name: '会话成员' })).toBeVisible()
  await expect(panel).toContainText('详情助手')
  await expect(panel).toContainText('fake-model')
  await panel.getByText('角色描述', { exact: true }).click()
  const content = panel.getByRole('region', { name: '会话详情内容' })
  await content.evaluate(element => { element.scrollTop = 150 })
  expect(await content.evaluate(element => element.scrollTop)).toBe(150)
  await trigger.click()
  await menu.getByRole('menuitemradio', { name: '会话概览' }).locator('span').last().click()
  await expect(menu).toHaveCount(0)
  await trigger.click()
  await menu.getByRole('menuitemradio', { name: '会话成员' }).locator('span').last().click()
  await expect(menu).toHaveCount(0)
  expect(await content.evaluate(element => element.scrollTop)).toBe(150)
  await expect(page.getByLabel('消息输入框')).toHaveValue('保留当前草稿')
  await expect(page).toHaveURL(new RegExp(`/conversation/${cid}$`))
  await trigger.click()
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await expect(menu).toHaveCount(0)
  await trigger.click()
  await page.getByLabel('消息输入框').click()
  await expect(menu).toHaveCount(0)
  await page.getByRole('button', { name: '关闭会话详情', exact: true }).click()
  await expect(panel).toHaveCount(0)
  await page.getByRole('button', { name: '打开会话详情', exact: true }).click()
  await expect(panel.getByRole('heading', { name: '会话成员' })).toBeVisible()
  await page.getByRole('button', { name: '会话进程', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '会话进程与详情' })).toBeVisible()
  await page.getByRole('button', { name: '关闭进程面板', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 850 })
  await page.getByRole('button', { name: '收起侧边栏', exact: true }).click()
  await page.getByRole('button', { name: '打开会话详情', exact: true }).click()
  const drawer = page.getByRole('dialog', { name: '会话详情', exact: true })
  await expect(drawer).toBeFocused()
  await trigger.click()
  await expect(menu).toBeVisible()
  await expect.poll(() => drawer.evaluate(el => el.scrollWidth - el.clientWidth)).toBeLessThanOrEqual(1)
  const mobile = testInfo.outputPath('details-mobile-menu.png')
  await page.screenshot({ path: mobile })
  await testInfo.attach('窄屏详情模块列表', { path: mobile, contentType: 'image/png' })
  await menu.getByRole('menuitemradio', { name: '会话概览' }).locator('span').last().click()
  await expect(menu).toHaveCount(0)
  await trigger.focus()
  await page.keyboard.press('Tab')
  await expect(drawer.getByRole('button', { name: /工作区：.*管理/ })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(trigger).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(drawer).toHaveCount(0)
  await expect(page.getByRole('button', { name: '打开会话详情', exact: true })).toBeFocused()
  await expect(page.getByLabel('消息输入框')).toHaveValue('保留当前草稿')
  const database = path.resolve(process.cwd(), process.env.ROLEPLEX_E2E_DATABASE_PATH!)
  execFileSync('python', ['tests/seed_tool_viewer.py', database, String(cid)], { cwd: path.resolve(process.cwd(), '../backend') })
  await page.evaluate(async ({ base, cid, stamp }) => {
    const response = await fetch(base + '/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ username: `test${stamp}_toolviewer`, password: 'Roleplex-Test-1234' }) })
    if (!response.ok) throw new Error('Guest 准备失败')
    localStorage.setItem('roleplex_token', (await response.json()).access_token)
    location.hash = `#/workspace/conversation/${cid}`
  }, { base, cid, stamp: process.env.ROLEPLEX_E2E_STAMP })
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.reload()
  await expect(panel).toBeVisible()
  await expect(panel.getByText('绑定工作区', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '会话进程', exact: true })).toHaveCount(0)
  await trigger.click()
  await menu.getByRole('menuitemradio', { name: '会话成员' }).locator('span').last().click()
  await expect(menu).toHaveCount(0)
  await expect(panel).toContainText(/角色 #\d+/)
  await expect(panel.getByRole('button', { name: '编辑角色：详情助手' })).toHaveCount(0)
  await expect(panel.getByText('fake-model', { exact: true })).toHaveCount(0)
  await expect(panel.getByText('角色描述', { exact: true })).toHaveCount(0)

})
